### ISSUE TITLE
what is the `open source lic` with this project?

### ISSUE THREAD

**Issue by Coloryr** [dragonman225/stm32f469-usbaudio-example#12]
Can i use this project code?

**Comment by dragonman225** [comment]
Good question! I didn't add a license because this was largely based on an [example project](https://github.com/STMicroelectronics/STM32CubeF4/tree/master/Projects/STM32469I-Discovery/Applications/USB_Device/AUDIO_Standalone) provided by STMicroelectronics, which also depended on several other STMicroelectronics' libraries with different licenses. At the moment, the example project had been removed, so it's becoming hard to find out the proper way to license this project.

In short, I don't recommend using this project in commercial products. But if you're tinkering with hobby projects for personal use, I think it's fine. In addition, this project hasn't been updated for 5 years, so it's better to just take inspiration from here and re-implement with newer example projects and libraries. You can find some technical insight and background knowledge in the [README](https://github.com/dragonman225/stm32f469-usbaudio/blob/master/README.md) and [git commit messages](https://github.com/dragonman225/stm32f469-usbaudio/commits/master/).
